name: msgfemr
channels:
  - conda-forge
dependencies:
  - python=3.12
  - fenics-dolfinx=0.8.0
  - fenics-basix=0.8.0
  - fenics-ffcx=0.8.0
  - fenics-libdolfinx=0.8.0
  - fenics-ufcx=0.8.0
  - fenics-ufl=2024.1.0
  - mpi4py
  - mpich  # or openmpi, depending on your needs
  - petsc
  - petsc4py
  - slepc
  - slepc4py
  - numpy
  - scipy
  - matplotlib-base
  - pyvista
  - pandas
  - pip
  - pip:
      - ray==2.47.1
      - jinja2
